name: Actions Runner Controller Demo
on:
  workflow_dispatch: null

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    # runs-on: arc-runner-set
    runs-on: arc-runner-set-my-image
    steps:
      - run: echo "ðŸŽ‰ This job uses runner scale set runners!"
