name: linters

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull-request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read
  checks: write

jobs:
  linters:
    name: linters
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/github-script@v8
        env:
          TITLE: '${{ github.event.pull_request.title }}'
        with:
          script: |
            const title = process.env.TITLE;
            console.log(`PR title: ${title}`);
            if (title.startsWith('octocat')) {
              console.log("PR title starts with 'octocat'");
            } else {
              console.error("PR title did not start with 'octocat'");
            }
      # - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12.12'
      - name: Install uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.1.3
        with:
          enable-cache: true
          cache-dependency-glob: requirements/*
      - run: uv venv
      - name: Install pre-commit
        run: uv pip install -r requirements/lint.txt # uv detects the virtual env
      - run: echo "$GITHUB_WORKSPACE/.venv/bin" >> "$GITHUB_PATH"
      - name: Restore/Cache pre-commit environment
        uses: actions/cache@v5
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: pre-commit run --all-files
